version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.5
    steps:
      - checkout
      - run: apt-cache policy
      - run: ruby -v
      - run: gem install bundler
      - run: bundle install
          
          
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
